### ISSUE TITLE
Colori grafico Evoluzione per provincia non leggibile

### ISSUE THREAD

**Issue by mpietro40** [lucianolorenti/coronITA#22]
Selezionando nella sezione "Evoluzione per provincia" la regione Lombardia il colore assegnato alla provincia di Pavia e' un giallo molto chiaro che non consente la lettura, se possibile sarebbe utile cambiare questo colore.

**Comment by lucianolorenti** [comment]
Thank you for the suggestion. I changed that color to be more visible.
Thank you again!
